// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL_w-efhwLmVqkbvfkcXBcbWxh0LXhNIk',
    appId: '1:536701431820:web:4cce17070d0436044b7e29',
    messagingSenderId: '536701431820',
    projectId: 'guardstudio-f3127',
    authDomain: 'guardstudio-f3127.firebaseapp.com',
    databaseURL: 'https://guardstudio-f3127-default-rtdb.firebaseio.com',
    storageBucket: 'guardstudio-f3127.appspot.com',
    measurementId: 'G-GVDXSYVVWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4o29vXWRrPAF8PHdrulfPFwRydtmifyA',
    appId: '1:536701431820:android:21a384f003ed3a4c4b7e29',
    messagingSenderId: '536701431820',
    projectId: 'guardstudio-f3127',
    databaseURL: 'https://guardstudio-f3127-default-rtdb.firebaseio.com',
    storageBucket: 'guardstudio-f3127.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC9E2xoxN5jveqmyq-tB8HkMXhI7uaps0',
    appId: '1:536701431820:ios:b5edb432f948fdc04b7e29',
    messagingSenderId: '536701431820',
    projectId: 'guardstudio-f3127',
    databaseURL: 'https://guardstudio-f3127-default-rtdb.firebaseio.com',
    storageBucket: 'guardstudio-f3127.appspot.com',
    iosBundleId: 'com.example.guardClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC9E2xoxN5jveqmyq-tB8HkMXhI7uaps0',
    appId: '1:536701431820:ios:b5edb432f948fdc04b7e29',
    messagingSenderId: '536701431820',
    projectId: 'guardstudio-f3127',
    databaseURL: 'https://guardstudio-f3127-default-rtdb.firebaseio.com',
    storageBucket: 'guardstudio-f3127.appspot.com',
    iosBundleId: 'com.example.guardClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBL_w-efhwLmVqkbvfkcXBcbWxh0LXhNIk',
    appId: '1:536701431820:web:53d8d1250907a6434b7e29',
    messagingSenderId: '536701431820',
    projectId: 'guardstudio-f3127',
    authDomain: 'guardstudio-f3127.firebaseapp.com',
    databaseURL: 'https://guardstudio-f3127-default-rtdb.firebaseio.com',
    storageBucket: 'guardstudio-f3127.appspot.com',
    measurementId: 'G-FLX4FDH6W5',
  );
}
