// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhXxfl6xH6LiHbesIZPjvsTNNTA6G-hMo',
    appId: '1:662945451244:web:6d3ba3ca60041f2c96e9c9',
    messagingSenderId: '662945451244',
    projectId: 'security-guard-691ff',
    authDomain: 'security-guard-691ff.firebaseapp.com',
    databaseURL: 'https://security-guard-691ff-default-rtdb.firebaseio.com',
    storageBucket: 'security-guard-691ff.appspot.com',
    measurementId: 'G-36TEGDTF2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANJoLg__fwpJJTSENv8EhAdVKjdATa-Mk',
    appId: '1:662945451244:android:0a2df224fe4de53596e9c9',
    messagingSenderId: '662945451244',
    projectId: 'security-guard-691ff',
    databaseURL: 'https://security-guard-691ff-default-rtdb.firebaseio.com',
    storageBucket: 'security-guard-691ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrbl3eXpOltdkCriOHIsgXGFhoFNwQcj8',
    appId: '1:662945451244:ios:278bb194a5f609e896e9c9',
    messagingSenderId: '662945451244',
    projectId: 'security-guard-691ff',
    databaseURL: 'https://security-guard-691ff-default-rtdb.firebaseio.com',
    storageBucket: 'security-guard-691ff.appspot.com',
    iosBundleId: 'com.example.guardClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrbl3eXpOltdkCriOHIsgXGFhoFNwQcj8',
    appId: '1:662945451244:ios:278bb194a5f609e896e9c9',
    messagingSenderId: '662945451244',
    projectId: 'security-guard-691ff',
    databaseURL: 'https://security-guard-691ff-default-rtdb.firebaseio.com',
    storageBucket: 'security-guard-691ff.appspot.com',
    iosBundleId: 'com.example.guardClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhXxfl6xH6LiHbesIZPjvsTNNTA6G-hMo',
    appId: '1:662945451244:web:01adfa6bb952f46b96e9c9',
    messagingSenderId: '662945451244',
    projectId: 'security-guard-691ff',
    authDomain: 'security-guard-691ff.firebaseapp.com',
    databaseURL: 'https://security-guard-691ff-default-rtdb.firebaseio.com',
    storageBucket: 'security-guard-691ff.appspot.com',
    measurementId: 'G-32KGQQGJ9K',
  );
}
